export const NEWS_CHANGE = "NEWS_CHANGE"
export const INPUT_CHANGE = "INPUT_CHANGE"
export const DATE_CHANGE = "DATE_CHANGE"
export const FOCUSE_CHANGE = "FOCUSE_CHANGE"
export const RESET_NEWS = "RESET_NEWS"
